spawns:
  lobby:
    px: 0.0
    py: 0.0
    pz: 0.0
    yaw: 0.0
    pitch: 0.0
  archer:
    px: 0.0
    py: 0.0
    pz: 0.0
    yaw: 0.0
    pitch: 0.0
  scout:
    px: 0.0
    py: 0.0
    pz: 0.0
    yaw: 0.0
    pitch: 0.0
  weegee:
    px: 0.0
    py: 0.0
    pz: 0.0
    yaw: 0.0
    pitch: 0.0
